name: "Setup poetry"
description: "Set up a specific version of poetry."
author: "Ondrej Winter"
inputs:
  poetry-version:
    description: "Exact version of poetry."
    default: 1.3.1
runs:
  using: "composite"
  steps:
    - name: Setup Poetry
      shell: bash
      run: |
        pip install --user poetry==${{inputs.poetry-version}}
